name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest 
    container:
        image: node:13.6
        options: --network-alias testHost
    env:
        SELENIUM_HUB_HOST: hub
        TEST_HOST: testHost
    services:
        hub:
          image: selenium/hub:3.141.59-gold
        firefox:
          image: selenium/node-firefox:3.141.59-gold
          env:
            HUB_HOST: hub
            HUB_PORT: 4444
    steps:          
      - name: Run jmeter step
        uses: kamipatel/jmeteraction@v417
        env:
            JMX_FILE_NAME: cputest.jmx  
        with:
          name: output
          path: output
      - shell: bash
        run: ls output            
      - name: Upload to EA
        uses: kamipatel/uploadaction@v40
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}  
        with:
          name: output
          path: output
      - shell: bash
        run: cat output/metrics.csv 
      - name: Upload action
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: output    

